name: Python application

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        python -m pip install -r services/web/requirements.txt
    
    - name: Docker build
      run: docker-compose build
      
    - name: Docker up
      run: docker-compose up -d

    - name: Test
      run:
#         |
#        cd services/web/project
#        python -m pip install -r ../requirements.txt
#        python __init__.py &
#        sleep 10
        python teste_api.py

    
    
    
